### PR TITLE
Fix references to morituri.

### LINKED ISSUE #100: Rename the Python module
From `morituri` to `whipper`. This should allow the two programs to be installed in parallel.

This should be done before 1.0 is released.

### PR DESCRIPTION
**Pull request by Freso**
Just adding so I can see my progress and get automated testing feedback. Started off as trying to fix #100, but then I started getting carried away. :)

See https://github.com/JoeLametta/whipper/pull/109#issuecomment-297452422 for details.

### CODE REVIEW

**Comment by Freso** [comment]
There are a number of lines with
> Morituri - for those about to RIP

It feels wrong to just replace `Morituri` with `Whipper`. Does whipper have a similar slogan (yet)? Should I just remove those lines?

File: doc/hacking/bugs/bgo-650785/bisect.sh [hunk 1]
```diff
@@ -1,10 +1,10 @@
 GOOD=/home/thomas/gst/git/gst-plugins-good/gst/audioparsers
-MORI=/home/thomas/dev/own/morituri
+WHIP=/home/thomas/dev/own/whipper
```
Comment (ArchangeGabriel) [inline doc/hacking/bugs/bgo-650785/bisect.sh]: Fixed reference to thomas’ PATH don’t look right anyway. What is this file? Just a bisect script he use(d) for some bugs?

Comment (JoeLametta) [inline doc/hacking/bugs/bgo-650785/bisect.sh]: Yeah, seems so.
I think that in the near future we'll probably `rm -r etc/bash_completion.d` (`doc/` replaced (?) and there's also lots of cruft in `misc/`).

**Comment by MerlijnWajer** [comment]
@JoeLametta shall we merge this one soon and prep a minor release? Might be useful for packagers.

**Comment by Freso** [comment]
I will try to catch up on this this week.

**Comment by JoeLametta** [comment]
> @JoeLametta shall we merge this one soon and prep a minor release? Might be useful for packagers.
> 
> EDIT: When it is ready to be merged and not just WIP, of course.

👍

**Comment by Freso** [comment]
Rebased on current master now that #130 has gone in.

There are a number of morituri references left (`git grep -i morituri`):
```
COVERAGE:$ coverage run --source=morituri --omit='morituri/test/*' -m unittest discover
COVERAGE:morituri/__init__.py                  10      2    80%   9, 11
COVERAGE:morituri/command/__init__.py           0      0   100%
COVERAGE:morituri/command/accurip.py           46     46     0%   23-100
COVERAGE:morituri/command/basecommand.py       58     42    28%   53-98, 105-114, 117, 120, 123, 126-129
COVERAGE:morituri/command/cd.py               273    232    15%   85-94, 100-209, 212, 224, 246-287, 293-316, 320-578
COVERAGE:morituri/command/debug.py            168    168     0%   23-297
COVERAGE:morituri/command/drive.py             62     62     0%   23-121
COVERAGE:morituri/command/image.py             74     74     0%   23-152
COVERAGE:morituri/command/main.py              55     55     0%   4-96
COVERAGE:morituri/command/offset.py           121    121     0%   23-241
COVERAGE:morituri/common/__init__.py            0      0   100%
COVERAGE:morituri/common/accurip.py            88     43    51%   40-42, 46, 49-65, 69-80, 83-94, 97-102
COVERAGE:morituri/common/cache.py             104     49    53%   67-91, 97, 100, 108-111, 114-115, 131, 143-148, 171-178, 202-207, 212-229
COVERAGE:morituri/common/checksum.py           33     18    45%   42, 45-46, 49-53, 60-65, 68-69, 72-76
COVERAGE:morituri/common/common.py            134     15    89%   51-52, 119-120, 142-143, 165, 259-265, 301-305
COVERAGE:morituri/common/config.py             85      9    89%   72, 97-98, 117-118, 124, 135, 137, 139
COVERAGE:morituri/common/directory.py          21      8    62%   30, 39, 43-50
COVERAGE:morituri/common/drive.py              31     20    35%   36-41, 45-51, 55-61, 65-73
COVERAGE:morituri/common/encode.py             44     23    48%   38-39, 42-43, 46-47, 53-56, 59-60, 63-64, 74-75, 78-79, 82-89
COVERAGE:morituri/common/mbngs.py             157     52    67%   39-40, 46, 91-97, 159-160, 165-166, 211, 214, 217, 238-240, 249, 269-321
COVERAGE:morituri/common/path.py               24      0   100%
COVERAGE:morituri/common/program.py           391    262    33%   90-92, 101-117, 125-157, 166-171, 174, 218, 230-231, 233-240, 247-253, 271-285, 292-415, 426-476, 484-492, 496-510, 521-560, 563-565, 575-584, 594-595, 664, 682-692, 695-703
COVERAGE:morituri/common/renamer.py           102      2    98%   138, 161
COVERAGE:morituri/common/task.py               77     19    75%   45-50, 85-86, 89-92, 100, 114-115, 122, 128, 134, 140, 147
COVERAGE:morituri/extern/__init__.py            0      0   100%
COVERAGE:morituri/extern/asyncsub.py          130     71    45%   15-17, 32, 37-38, 47-84, 89-102, 115, 122, 133, 144, 150, 155-159, 162-174
COVERAGE:morituri/extern/task/__init__.py       0      0   100%
COVERAGE:morituri/extern/task/task.py         272    114    58%   49, 53, 80, 83, 86, 153-154, 171-173, 181-197, 215-217, 238-239, 279-280, 283-289, 303-304, 312-314, 323-330, 336-352, 356, 359, 366-383, 394-395, 398-401, 405, 408, 422, 425-427, 442, 454, 498-503, 513-518, 529-537, 540-549, 552-553, 561, 565-567
COVERAGE:morituri/image/__init__.py             0      0   100%
COVERAGE:morituri/image/cue.py                 91      9    90%   101, 118-119, 135-137, 161, 189, 207
COVERAGE:morituri/image/image.py              138    110    20%   52-60, 68-70, 77-110, 122-145, 148-149, 163-195, 198-214, 225-255
COVERAGE:morituri/image/table.py              403     22    95%   240, 355-356, 555, 635, 718-719, 740-741, 749-752, 756-757, 802, 848-849, 851-852, 861-862, 867-869
COVERAGE:morituri/image/toc.py                204     15    93%   136, 263-264, 280-283, 345-347, 369-371, 391, 415
COVERAGE:morituri/program/__init__.py           0      0   100%
COVERAGE:morituri/program/arc.py               35     28    20%   11-52
COVERAGE:morituri/program/cdparanoia.py       312    183    41%   50-52, 61-62, 126-128, 167-170, 243-257, 260-310, 313-351, 354-358, 361-395, 450-501, 506-552, 584-587, 590, 597, 603, 608-613
COVERAGE:morituri/program/cdrdao.py            44     23    48%   24-46, 55-57, 61-63, 70, 76
COVERAGE:morituri/program/flac.py               9      5    44%   11-18
COVERAGE:morituri/program/sox.py               15      4    73%   17-18, 22-23
COVERAGE:morituri/program/soxi.py              28      2    93%   35, 48
COVERAGE:morituri/program/utils.py             16     10    38%   11-12, 19-20, 30-35
COVERAGE:morituri/result/__init__.py            0      0   100%
COVERAGE:morituri/result/logger.py            137    137     0%   1-224
COVERAGE:morituri/result/result.py             57     10    82%   127, 145, 155-156, 165-172
README.md:Whipper is a Python 2 CD-DA ripper, fork of the morituri project (_CDDA ripper for *nix systems aiming for accuracy over speed_). It improves morituri which development seems to have halted merging old ignored pull requests, improving it with bugfixes and new features.
README.md:For a detailed description, see morituri's wiki page: [The Art of the Rip](
README.md:    - `.moriturirc`, `morituri.conf` aren't used anymore
README.md:- [morituri-yamlloger](https://github.com/JoeLametta/morituri-yamllogger) - default whipper logger (provided as external logger for compatibility with morituri), yaml format
README.md:- [morituri-eaclogger](https://github.com/JoeLametta/morituri-eaclogger) - eac-like logger attempting to maintain strict compatiility with EAC
README.md:- [morituri-whatlogger](https://github.com/RecursiveForest/morituri-whatlogger) - eac-like logger containing the informational enhancements of the yamllogger, originally designed for use on What.CD
TODO:  DEBUG [13888] "ChecksumTask 0xb5e8b290"        ChecksumTask      Jul 25 19:09:47      bus_error_cb: bus <gst.Bus object (bus2) at 0xb5e940a8>, message <gst.Message GstMessageError, gerror=(GError)NULL, debug=(string)"/var/tmp/portage/media-libs/gst-plugins-base-0.10.36-r1/work/gst-plugins-base-0.10.36/gst/playback/gstdecodebin.c\(1003\):\ close_pad_link\ \(\):\ /GstPipeline:pipeline0/GstDecodeBin:decode:\012No\ decoder\ to\ handle\ media\ type\ \'audio/x-wav\'"; from decode at 0x7f74fea8> (morituri/extern/task/gstreamer.py:211)
TODO:DEBUG [13888] "ChecksumTask 0xb5e8b290"        ChecksumTask      Jul 25 19:09:47      set exception, 'exception GstException at /home/merlijn/archive/morituri/morituri/extern/task/gstreamer.py:217: bus_error_cb(): (<GError at 0x7f7f5360>, "/var/tmp/portage/media-libs/gst-plugins-base-0.10.36-r1/work/gst-plugins-base-0.10.36/gst/playback/gstdecodebin.c(1003): close_pad_link (): /GstPipeline:pipeline0/GstDecodeBin:decode:\\nNo decoder to handle media type \'audio/x-wav\'")' (morituri/extern/task/task.py:197)
doc/release:Release procedure for morituri
doc/release:  http://packages.qa.debian.org/m/morituri.html
doc/release:  http://patch-tracker.debian.org/package/morituri
doc/release:  ls /tmp/*morituri*
doc/release:  https://thomas.apestaart.org/morituri/trac/query?order=priority&col=id&col=summary&col=status&col=type&col=priority&col=milestone&col=component&milestone=0.1.1
doc/release:  https://github.com/thomasvs/morituri/issues?milestone=4&page=1&state=open
doc/release:  https://github.com/thomasvs/morituri/issues?milestone=4&page=1&state=closed
doc/release:  cat morituri/configure/installed.py | grep revision
doc/release:  rpmbuild -ta morituri-$VERSION.tar.bz2
doc/release:  mach -r f19u64 -k build morituri.spec
doc/release:  rpm --addsign /var/tmp/mach/fedora-*/morituri-$VERSION-*/*.rpm
doc/release:  sudo rpm -Uhv /var/tmp/mach/fedora-*/morituri-$VERSION-*/*.noarch.rpm
doc/release:  cp morituri-$VERSION.tar* /home/thomas/www/thomas.apestaart.org/data/download/morituri
doc/release:  cp /var/tmp/mach/fedora-*/morituri-$VERSION-*/*.rpm /home/thomas/www/thomas.apestaart.org/data/download/morituri
doc/release:    moap doap -v $VERSION mail -f thomas${AT}apestaart.org cdrdao-devel${AT}lists.sourceforge.net teuf${AT}gnome.org morituri${AT}packages.debian.org
whipper/common/common.py:    # See https://thomas.apestaart.org/morituri/trac/ticket/107
whipper/common/encode.py:# program/cdparanoia.py - where morituri currently does the tagging.
whipper/extern/task/ChangeLog:	  Was triggered by morituri's checksum test, but only
whipper/program/cdrdao.py:    # hack is carried from morituri to whipper and will be removed when
whipper/program/cdrdao.py:    stopgap morituri-insanity compatibility layer
whipper/program/cdrdao.py:    stopgap morituri-insanity compatibility layer
whipper/program/cdrdao.py:    stopgap morituri-insanity compatibility layer
Binary file whipper/test/cache/result/fe105a11.pickle matches
whipper/test/test_common_mbngs.py:        # see https://github.com/thomasvs/morituri/issues/19
```

- The `COVERAGE` one states it's based on version 0.5.1, so I don't want to update that—I guess it'll be updated for the next release.
- `TODO`, `doc/release`, and `whipper/extern/task/ChangeLog` seem to be files that are going to go away, so I don't care to fix those up too much.
- The line in `whipper/common/encode.py` ("where morituri currently does the tagging.") could either be seen as a historical comment ("this is how morituri does/did it"), but if it actually refers to whipper's behaviour, it should probably be updated. @JoeLametta?
- I tried updated the paths in `whipper/test/cache/result/fe105a11.pickle` with `sed`, but this made the tests fail. It worked for the other .pickle files and doesn't seem to have any consequence, so I just left this out.
- The rest seems to be genuine comments about e.g., the historical relationship with morituri or describing differences between morituri and whipper.

**Comment by JoeLametta** [comment]
> The COVERAGE one states it's based on version 0.5.1, so I don't want to update that—I guess it'll be updated for the next release.

Correct.

> TODO, doc/release, and whipper/extern/task/ChangeLog seem to be files that are going to go away, so I don't care to fix those up too much.

;)

> The line in whipper/common/encode.py ("where morituri currently does the tagging.") could either be seen as a historical comment ("this is how morituri does/did it"), but if it actually refers to whipper's behaviour, it should probably be updated. @JoeLametta?

It could be changed in the future but, right now, that's still true (so 'morituri' can be replaced with 'whipper' in that comment).

> I tried updated the paths in whipper/test/cache/result/fe105a11.pickle with sed, but this made the tests fail. It worked for the other .pickle files and doesn't seem to have any consequence, so I just left this out.

OK

> The rest seems to be genuine comments about e.g., the historical relationship with morituri or describing differences between morituri and whipper.

👍

**Comment by Freso** [comment]
Changed the text in `whipper/common/encode.py` as well.

File: whipper/test/common.py [hunk 2]
```diff
@@ -70,8 +70,8 @@ def readCue(self, name):
         ret = open(os.path.join(os.path.dirname(__file__), name)).read(
             ).decode('utf-8')
         ret = re.sub(
-            'REM COMMENT "Morituri.*',
-            'REM COMMENT "Morituri %s"' % (morituri.__version__),
+            'REM COMMENT "Whipper.*',
+            'REM COMMENT "Whipper %s"' % (whipper.__version__),
             ret, re.MULTILINE)
```
Comment (tobbez) [inline whipper/test/common.py]: I think the original code is broken here. All the cue sheets used in the tests have 'morituri' in all lower case (and so does the code that generates those lines). Since the regular expression doesn't ignore case, that means the substitution currently has no effect.

This doesn't have to be fixed in this PR, but it should be fixed (by making it "whipper" rather than "Whipper").

**Comment by MerlijnWajer** [comment]
Looks good to me! Thanks.

File: whipper/test/common.py (hunk 2 above)
Comment (JoeLametta) [inline whipper/test/common.py]: Good catch.
Yeah, it looks like a mistake: I'll fix it in a separate commit.
